<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>JellyClip</RootNamespace>
    <AssemblyName>JellyClip</AssemblyName>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.*-*" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.*-*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <None Remove="Configuration\jellyclip.js" />
    <EmbeddedResource Include="Configuration\jellyclip.js" />
    <None Remove="Configuration\jellyclip.css" />
    <EmbeddedResource Include="Configuration\jellyclip.css" />
  </ItemGroup>

</Project>